install.packages("ggplot2")
install.packages("archdata")
install.packages("RCurl")
install.packages("jsonlite")
install.packages("rvest")
install.packages("dplyr")
install.packages("topicmodels")
install.packages("tidyverse")
